### ISSUE TITLE
某校校歌のアーティスト表示について

### ISSUE THREAD

**Issue by KusaReMKN** [sasakulab/sasakulab.com#1]
こんにちは、右コーナーで差をつけられて大爆笑しております :smile:

さて、アーティストの欄についてですが、校歌の作詞は**西月 拓**、作曲は**兼原 直恭**となっております。これらは私の別名では**ありません**。そのため、アーティストの項目に KusaReMKN が表示されることは不適切なのかもしれません。

ところで、それ以外の曲を眺めてみると、作詞作曲者ではなくそれを歌っている人やグループ名であるようです。私はここに作詞作曲者を表示させるべきか躊躇しました。

P.S. `quote`( ) で生成される URL を利用して検索してみましたが、作詞作曲者名でも KusaReMKN でも検索には引っ掛るようです。

**Comment by sasakulari** [comment]
KusaReMKN 様

いつもお世話になっております。

さて、この度はお知らせいただきありがとうございます。
お察しの通り、**検索に引っかかる** という理由のみで KusaReMKN 様のお名前を掲載しました。
しかし、検索エンジンでヒットするのであれば、作詞者名のほうが良いように思います。
@yude 様のサイトを参照すると、引用元のお名前は **西月 拓** 様のお名前になっていることが確認できました。

https://github.com/yudejp/yude.jp_v4/blob/main/public/assets/quotes.json

学校ホームページの運営プロバイダである @KusaReMKN 様のご意向が最優先だと思いますが、とくにこだわりがなければ、西月様のお名前を掲載するように変更をかけようと思います。

今後ともよろしくお願いいたします。

==========
ささくらり

**Comment by KusaReMKN** [comment]
西月ちゃんにしちゃいましょう！

**Comment by sasakulari** [comment]
ok

**Comment by sasakulari** [comment]
![image](https://user-images.githubusercontent.com/58127312/224488158-8ae19380-2647-4306-9927-9d4493480148.png)
Updated, Close
